### ISSUE TITLE
[FEAT] User limit for admins

### ISSUE THREAD

**Issue by alfirovich** [marzneshin/marzneshin#468]
### Description

Add a limit on the number of users created by other administrators

### Suggested Solution

It would not be superfluous to add a limit on the maximum number of users created by other administrators

**Comment by Krr0ptioN** [comment]
#73

**Comment by khodedawsh** [comment]
I thought this is a pretty good idea but after thinking it through I concluded there are no actual points in this unless there are limits to how much resource(traffic rn) the admin could allocate for each user.
in that case traffic allocation would be limited. limiting the allocation is generally not a good idea since the admin could just merge all its users together and reset the traffic everyday.
but I'm willing to discuss this further, you could try to prove me wrong.

**Comment by m0x61h0x64i** [comment]
we need device limit, but how?

**Comment by erfjab** [comment]
> we need device limit, but how?
First, why?, 👀

**Comment by erfjab** [comment]
> we need device limit, but how?

First, Why?
